#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
#  make a symlink to 'python'
PROJECT_NAME := wlan_and_counter

include $(IDF_PATH)/make/project.mk

